DATA:
  data_name: shapenetpart
  data_root: ./data/shapenetpart
  npoints: 2048
  use_normals: False

Transfer:
  transfer_model_path: Exp/ModelNet40/p2p_ConvNeXt-B-1k/model/model_last.pth
  classes: 40
  

BaseModel:
  base_model_variant: convnext_base
  head_type: linear
  obj_size: 224
  img_size: 224
  checkpoint_path:

Enc:
  local_size: 32
  trans_dim: 8
  graph_dim: 64
  imgblock_dim: 64
  imagenet_default_mean: [0.485, 0.456, 0.406]
  imagenet_default_std: [0.229, 0.224, 0.225]

TRAIN:
  update_type: norm
  label_smoothing: True

  train_gpu: [0]
  workers: 4
  batch_size: 32
  batch_size_val: 32
  
  lr: 5e-4
  weight_decay: 0.05
  epochs: 40
  start_epoch: 0
  warmup_epochs: 0
  scheduler: CosLR

  manual_seed: 1463
  print_freq: 40
  save_freq: 1
  save_path:
  pretrained: 
  weight:  # path to initial weight (default: none)
  resume: 
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

Distributed:
  dist_url: tcp://127.0.0.1:3832
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0


TEST:
  test_workers: 2
  test_gpu: [0]
  test_batch_size: 32
  model_path:
  save_folder:
